//! Locale resolution and message lookup.
//!
//! Three-tier fallback: browser preference → explicit cookie → en-US. Locale is chosen at startup
//! and stays stable for the session, because a locale that changes mid-workflow breaks more than it
//! helps: someone who set their browser to French and is now looking at an English error should not
//! also have to re-find the button they were clicking when the language swapped under them.
//!
//! Messages live in JSON files under `static/i18n/literals/`, served by the host's existing
//! `/i18n/literals/{tag}.json` route -- which already strips traversal, so a crafted locale tag
//! cannot escape the static root. The build does not load them; the dashboard fetches its own
//! locale file at startup, which keeps i18n out of the Rust build and lets translations land
//! without a wasm rebuild.
//!
//! Files are generated by `tools/i18n-gen`, never hand-edited. The generator is also what carries
//! the pre-existing translations forward: those files were keyed by English source sentence
//! (`"Cancel": "Annuler"`), and this module needs them keyed by `section.key`, so the generator
//! bridges the two by looking each English value up in the old map.

use leptos::prelude::*;
use std::collections::HashMap;

/// Which locale the dashboard resolved to.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
// Cheap to clone: the table is small and every nested view! closure that needs
// a message has to own a copy. Copy would be nicer, but HashMap is not Copy.
pub struct Locale {
    /// IETF language tag, e.g. `"en-US"`.
    pub tag: String,
    /// Message table, keyed by `"section.key"`.
    messages: HashMap<String, String>,
}

impl Locale {
    /// Look up a message, falling back to the key itself when the entry is missing.
    ///
    /// A missing key renders as itself rather than crashing or rendering blank space, so an
    /// incomplete translation file degrades to showing English keys (which are readable) instead of
    /// taking the panel down.
    pub fn get<'a>(&'a self, key: &'a str) -> &'a str {
        self.messages.get(key).map_or(key, String::as_str)
    }

    /// Shorthand for formatted messages. Call as `locale.fmt("settings.account_created", &[("name", "alice")])`.
    pub fn fmt(&self, key: &str, replacements: &[(&str, &str)]) -> String {
        let mut text = self.get(key).to_owned();
        for (placeholder, value) in replacements {
            text = text.replace(&format!("{{{placeholder}}}"), value);
        }
        text
    }

    /// Deserialize a fetched locale file.
    // Called from `load_locale`, which only exists on wasm32, and from the tests. On a native
    // non-test build it therefore has no callers.
    #[cfg_attr(
        all(not(test), not(target_arch = "wasm32")),
        expect(dead_code, reason = "load_locale, its only caller, is wasm32-only")
    )]
    fn parse(tag: String, json: &str) -> Result<Self, String> {
        let messages: HashMap<String, String> =
            serde_json::from_str(json).map_err(|error| format!("locale parse failed: {error}"))?;
        Ok(Self { tag, messages })
    }
}

/// Locale files that exist, and the only tags a fetch may ask for.
///
/// Kept as a list rather than probing the network: an unknown tag would otherwise cost a 404 per
/// candidate before falling back, and the set only changes when a file is added.
pub const AVAILABLE: [&str; 35] = [
    "ar", "bn", "cs", "da", "de", "el", "en-US", "es", "fa", "fi", "fr", "he", "hi", "hu", "id",
    "it", "ja", "km", "ko", "nl", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sv", "th", "tl", "tr",
    "uk", "ur", "vi", "zh-CN", "zh-TW",
];

/// Resolve a browser or cookie tag to a file that actually exists.
///
/// Browsers send region-qualified tags (`de-DE`, `en-GB`, `zh-Hans-CN`) while most catalogues are
/// bare languages, so an exact-match-only lookup would 404 for nearly every non-English visitor and
/// render raw message keys. The chain is: exact match, then the bare language, then the first
/// regional file for that language, then `en-US`.
pub fn resolve_tag(requested: &str) -> &'static str {
    let requested = requested.trim();

    if let Some(exact) = AVAILABLE
        .iter()
        .find(|tag| tag.eq_ignore_ascii_case(requested))
    {
        return exact;
    }

    // `zh-Hans-CN` -> `zh`; also the whole tag when there is no separator.
    let language = requested
        .split(['-', '_'])
        .next()
        .unwrap_or(requested)
        .to_ascii_lowercase();
    if language.is_empty() {
        return "en-US";
    }

    if let Some(bare) = AVAILABLE
        .iter()
        .find(|tag| tag.eq_ignore_ascii_case(&language))
    {
        return bare;
    }

    // `en-GB` has no `en.json`, but `en-US.json` is the right answer; likewise `zh-MO` -> `zh-CN`.
    if let Some(regional) = AVAILABLE.iter().find(|tag| {
        tag.split('-')
            .next()
            .is_some_and(|prefix| prefix.eq_ignore_ascii_case(&language))
    }) {
        return regional;
    }

    "en-US"
}

/// Detect the user's preferred locale and load its message table.
///
/// Tries: explicit `locale` cookie → browser's `navigator.languages` → `en-US`. Returns the loaded
/// locale and also puts it in context.
///
/// This runs on mount, so it *will* delay first paint by one request. That is deliberate: rendering
/// English placeholder text and then swapping every label is more disruptive than a slightly longer
/// load, and the file is small (under 20 KB even with every panel's messages).
#[cfg(target_arch = "wasm32")]
pub async fn provide_locale() -> Locale {
    let requested = detect_locale().unwrap_or_else(|| "en-US".to_owned());
    let tag = resolve_tag(&requested);
    let mut loaded = load_locale(tag).await;
    // A resolved tag that still fails to load is a missing or corrupt file, not a bad preference.
    // English is the authoritative catalogue, so it is worth one more request before giving up.
    if loaded.is_err() && tag != "en-US" {
        loaded = load_locale("en-US").await;
    }
    let locale = loaded.unwrap_or_else(|_| Locale {
        tag: "en-US".to_owned(),
        messages: HashMap::new(),
    });
    provide_context(locale.clone());
    locale
}

/// Native builds have no browser to detect from or fetch through.
#[cfg(not(target_arch = "wasm32"))]
#[expect(
    clippy::unused_async,
    reason = "mirrors the wasm signature so callers stay target-agnostic"
)]
pub async fn provide_locale() -> Locale {
    let locale = Locale {
        tag: "en-US".to_owned(),
        messages: HashMap::new(),
    };
    provide_context(locale.clone());
    locale
}

/// The locale from context.
///
/// Falls back to an empty en-US rather than panicking, so a component rendered outside the provider
/// degrades to showing message keys instead of crashing.
pub fn use_locale() -> Locale {
    use_context::<Locale>().unwrap_or_else(|| Locale {
        tag: "en-US".to_owned(),
        messages: HashMap::new(),
    })
}

/// Read the user's locale preference from the cookie or the browser.
#[cfg(target_arch = "wasm32")]
fn detect_locale() -> Option<String> {
    use wasm_bindgen::JsCast;

    let window = web_sys::window()?;
    let document = window.document()?;

    // `cookie()` lives on `HtmlDocument`, not `Document`, so reading it needs the cast.
    if let Some(cookies) = document
        .dyn_ref::<web_sys::HtmlDocument>()
        .and_then(|html| html.cookie().ok())
    {
        for pair in cookies.split(';') {
            if let Some(value) = pair
                .trim()
                .strip_prefix("locale=")
                .filter(|v| !v.is_empty())
            {
                return Some(value.to_owned());
            }
        }
    }

    // Otherwise the browser's first supported language.
    let navigator = window.navigator();
    let languages = navigator.languages();
    if languages.length() > 0 {
        return languages.get(0).as_string();
    }

    None
}

/// Fetch and parse a locale file.
#[cfg(target_arch = "wasm32")]
async fn load_locale(tag: &str) -> Result<Locale, String> {
    let path = format!("/i18n/literals/{tag}.json");
    let body = crate::api::get(&path)
        .await
        .map_err(|error| format!("fetch {path} failed: {error:?}"))?;
    Locale::parse(tag.to_owned(), &body)
}

#[cfg(test)]
mod tests {
    use super::{AVAILABLE, Locale, resolve_tag};

    #[test]
    fn an_exact_tag_is_used_as_is() {
        assert_eq!(resolve_tag("pt-BR"), "pt-BR");
        assert_eq!(resolve_tag("ja"), "ja");
    }

    #[test]
    fn a_region_falls_back_to_the_bare_language() {
        assert_eq!(resolve_tag("de-DE"), "de");
        assert_eq!(resolve_tag("fr-CA"), "fr");
    }

    #[test]
    fn a_language_with_only_regional_files_picks_one() {
        // There is no `en.json` or `zh.json`; both must still resolve.
        assert_eq!(resolve_tag("en-GB"), "en-US");
        assert_eq!(resolve_tag("en"), "en-US");
        assert!(resolve_tag("zh-Hans-CN").starts_with("zh-"));
    }

    #[test]
    fn tags_are_matched_case_insensitively_and_accept_underscores() {
        assert_eq!(resolve_tag("PT-br"), "pt-BR");
        assert_eq!(resolve_tag("de_DE"), "de");
    }

    #[test]
    fn an_unknown_or_empty_language_falls_back_to_english() {
        assert_eq!(resolve_tag("xx-YY"), "en-US");
        assert_eq!(resolve_tag(""), "en-US");
        assert_eq!(resolve_tag("   "), "en-US");
    }

    #[test]
    fn every_available_tag_resolves_to_itself() {
        for tag in AVAILABLE {
            assert_eq!(resolve_tag(tag), tag, "{tag} did not round-trip");
        }
    }

    #[test]
    fn missing_keys_fall_back_to_themselves() {
        let locale = Locale {
            tag: "en-US".to_owned(),
            messages: [].into(),
        };
        assert_eq!(locale.get("missing.key"), "missing.key");
    }

    #[test]
    fn present_keys_return_their_messages() {
        let locale = Locale {
            tag: "en-US".to_owned(),
            messages: [("app.title".to_owned(), "Router".to_owned())].into(),
        };
        assert_eq!(locale.get("app.title"), "Router");
    }

    #[test]
    fn fmt_replaces_placeholders() {
        let locale = Locale {
            tag: "en-US".to_owned(),
            messages: [("greeting".to_owned(), "Hello, {name}!".to_owned())].into(),
        };
        assert_eq!(
            locale.fmt("greeting", &[("name", "Alice")]),
            "Hello, Alice!"
        );
    }

    #[test]
    fn fmt_handles_multiple_replacements() {
        let locale = Locale {
            tag: "en-US".to_owned(),
            messages: [(
                "status".to_owned(),
                "{count} items in {container}".to_owned(),
            )]
            .into(),
        };
        assert_eq!(
            locale.fmt("status", &[("count", "5"), ("container", "queue")]),
            "5 items in queue"
        );
    }

    #[test]
    fn missing_keys_in_fmt_still_fall_back_to_the_key() {
        let locale = Locale {
            tag: "en-US".to_owned(),
            messages: [].into(),
        };
        assert_eq!(locale.fmt("missing.key", &[("x", "y")]), "missing.key");
    }

    #[test]
    fn parse_deserializes_a_message_table() {
        let json = r#"{"app.title": "Router", "app.subtitle": "Gateway"}"#;
        let locale = Locale::parse("en-US".to_owned(), json).expect("valid JSON");
        assert_eq!(locale.tag, "en-US");
        assert_eq!(locale.get("app.title"), "Router");
        assert_eq!(locale.get("app.subtitle"), "Gateway");
    }

    #[test]
    fn parse_rejects_malformed_json() {
        assert!(Locale::parse("en-US".to_owned(), "{not valid").is_err());
    }
}
