use crate::catalog::RouteFamily;

pub(crate) const ROUTE_FAMILIES: [RouteFamily; 3] = [
    RouteFamily {
        id: "api",
        title: "Control API",
        upstream: "nullrouter-api",
        gateway_prefix: "/api",
        source_prefix: "/api",
        routes: &API_ROUTES,
    },
    RouteFamily {
        id: "v1",
        title: "OpenAI-compatible API",
        upstream: "nullrouter-runtime",
        gateway_prefix: "/v1",
        source_prefix: "/v1",
        routes: &V1_ROUTES,
    },
    RouteFamily {
        id: "dashboard",
        title: "Dashboard host",
        upstream: "nullrouter-dashboard-host",
        gateway_prefix: "/",
        source_prefix: "/",
        routes: &DASHBOARD_ROUTES,
    },
];

const API_ROUTES: [&str; 25] = [
    "/api/health",
    "/api/auth/status",
    "/api/settings",
    "/api/keys",
    "/api/models",
    "/api/dashboard/chat/completions",
    "/api/translator/load",
    "/api/translator/save",
    "/api/translator/translate",
    "/api/translator/send",
    "/api/translator/console-logs",
    "/api/translator/console-logs/stream",
    "/api/proxy-pools",
    "/api/proxy-pools/{id}",
    "/api/proxy-pools/{id}/test",
    "/api/proxy-pools/vercel-deploy",
    "/api/proxy-pools/cloudflare-deploy",
    "/api/proxy-pools/deno-deploy",
    "/api/providers/client",
    "/api/providers",
    "/api/media-providers/tts/voices",
    "/api/media-providers/tts/{provider}/voices",
    "/api/usage/stats",
    "/api/cli-tools/antigravity-mitm",
    "/api/cli-tools/antigravity-mitm/alias",
];

const V1_ROUTES: [&str; 10] = [
    "/v1",
    "/v1/models",
    "/v1/chat/completions",
    "/v1/responses",
    "/v1/messages",
    "/v1/audio/speech",
    "/v1/embeddings",
    "/v1/images/generations",
    "/v1/search",
    "/v1/web/fetch",
];

const DASHBOARD_ROUTES: [&str; 28] = [
    "/",
    "/dashboard",
    "/dashboard/{path:.*}",
    "/dashboard/endpoint",
    "/dashboard/basic-chat",
    "/dashboard/providers",
    "/dashboard/providers/new",
    "/dashboard/providers/{id}",
    "/dashboard/media-providers/web",
    "/dashboard/media-providers/embedding",
    "/dashboard/media-providers/{kind}",
    "/dashboard/media-providers/{kind}/{id}",
    "/dashboard/media-providers/combo/{id}",
    "/dashboard/usage",
    "/dashboard/status",
    "/dashboard/combos",
    "/dashboard/settings",
    "/dashboard/settings/pricing",
    "/dashboard/proxy-pools",
    "/dashboard/translator",
    "/dashboard/console-log",
    "/dashboard/quota",
    "/dashboard/token-saver",
    "/dashboard/cli-tools",
    "/dashboard/cli-tools/{toolId}",
    "/dashboard/skills",
    "/dashboard/profile",
    "/dashboard/mitm",
];
